/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aff3ct_interleaver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(beb484d16feea305944ee2b538bdf7a1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/aff3ct_interleaver.h>
// pydoc.h is automatically generated in the build directory
#include <aff3ct_interleaver_pydoc.h>

void bind_aff3ct_interleaver(py::module& m)
{


    py::module m_Interleaver = m.def_submodule("Interleaver");


    py::enum_<::gr::fec_dev::Interleaver::_interleaver_t>(m_Interleaver, "_interleaver_t")
        .value("LTE", ::gr::fec_dev::Interleaver::_interleaver_t::LTE)           // 0
        .value("CCSDS", ::gr::fec_dev::Interleaver::_interleaver_t::CCSDS)       // 1
        .value("NO", ::gr::fec_dev::Interleaver::_interleaver_t::NO)             // 2
        .value("COL_ROW", ::gr::fec_dev::Interleaver::_interleaver_t::COL_ROW)   // 3
        .value("ROW_COL", ::gr::fec_dev::Interleaver::_interleaver_t::ROW_COL)   // 4
        .value("RANDOM", ::gr::fec_dev::Interleaver::_interleaver_t::RANDOM)     // 5
        .value("RAND_COL", ::gr::fec_dev::Interleaver::_interleaver_t::RAND_COL) // 6
        .value("GOLDEN", ::gr::fec_dev::Interleaver::_interleaver_t::GOLDEN)     // 7
        .value("DVB_RCS1", ::gr::fec_dev::Interleaver::_interleaver_t::DVB_RCS1) // 8
        .value("DVB_RCS2", ::gr::fec_dev::Interleaver::_interleaver_t::DVB_RCS2) // 9
        .export_values();

    py::implicitly_convertible<int, ::gr::fec_dev::Interleaver::_interleaver_t>();
    py::enum_<::gr::fec_dev::Interleaver::_itl_read_order_t>(m_Interleaver,
                                                             "_itl_read_order_t")
        .value("TOP_LEFT", ::gr::fec_dev::Interleaver::_itl_read_order_t::TOP_LEFT)   // 0
        .value("TOP_RIGHT", ::gr::fec_dev::Interleaver::_itl_read_order_t::TOP_RIGHT) // 1
        .value("BOTTOM_LEFT",
               ::gr::fec_dev::Interleaver::_itl_read_order_t::BOTTOM_LEFT) // 2
        .value("BOTTOM_RIGHT",
               ::gr::fec_dev::Interleaver::_itl_read_order_t::BOTTOM_RIGHT) // 3
        .value("NA", ::gr::fec_dev::Interleaver::_itl_read_order_t::NA)     // -1
        .export_values();

    py::implicitly_convertible<int, ::gr::fec_dev::Interleaver::_itl_read_order_t>();
}
