/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bch_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f0ea0e98f93d42b89a58877b6ce6a486)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/bch_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <bch_encoder_pydoc.h>

void bind_bch_encoder(py::module& m)
{

    using bch_encoder = gr::fec_dev::bch_encoder;


    py::class_<bch_encoder, gr::fec::generic_encoder,
        std::shared_ptr<bch_encoder>>(m, "bch_encoder", D(bch_encoder))

        .def_static("make", &bch_encoder::make,
           py::arg("frame_bits"),
           py::arg("t") = 5,
           py::arg("simd_strat") = ::gr::fec_dev::SIMD::_simd_strat_t::SEQ,
           D(bch_encoder,make)
        )

        .def("set_frame_size",
            &bch_encoder::set_frame_size,
            py::arg("frame_bits"),
            D(bch_encoder, set_frame_size))

        .def("rate", &bch_encoder::rate, D(bch_encoder, rate))

        ;
}








