/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bcjr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2086ac1f2a876daea43a30680354827c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/bcjr.h>
// pydoc.h is automatically generated in the build directory
#include <bcjr_pydoc.h>

void bind_bcjr(py::module& m)
{
    py::enum_<::gr::fec_dev::_bcjr_impl_t>(m, "_bcjr_impl_t")
        .value("STD", ::gr::fec_dev::_bcjr_impl_t::STD)
        .value("FAST", ::gr::fec_dev::_bcjr_impl_t::FAST)
        .value("VERY_FAST", ::gr::fec_dev::_bcjr_impl_t::VERY_FAST)
        .value("SCAN", ::gr::fec_dev::_bcjr_impl_t::SCAN)
        .value("GENERIC", ::gr::fec_dev::_bcjr_impl_t::GENERIC)
        .export_values();
    py::implicitly_convertible<int, ::gr::fec_dev::_bcjr_impl_t>();

    py::enum_<::gr::fec_dev::_simd_interintra_impl_t>(m, "_simd_interintra_impl_t")
        .value("X2_AVX", ::gr::fec_dev::_simd_interintra_impl_t::X2_AVX)
        .value("X2_SSE", ::gr::fec_dev::_simd_interintra_impl_t::X2_SSE)
        .value("X4_AVX", ::gr::fec_dev::_simd_interintra_impl_t::X4_AVX)
        .export_values();
    py::implicitly_convertible<int, ::gr::fec_dev::_simd_interintra_impl_t>();
}