/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(polar_decoder_aff3ct.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a0a6c64e55d2682371a8d0342c1506ba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/polar_decoder_aff3ct.h>
// pydoc.h is automatically generated in the build directory
#include <polar_decoder_aff3ct_pydoc.h>

void bind_polar_decoder_aff3ct(py::module& m)
{
    using polar_decoder_aff3ct = ::gr::fec_dev::polar_decoder_aff3ct;


    py::class_<polar_decoder_aff3ct, gr::fec::generic_decoder,
        std::shared_ptr<polar_decoder_aff3ct>>(m, "polar_decoder_aff3ct", D(polar_decoder_aff3ct))

        .def_static("make", &polar_decoder_aff3ct::make,
           py::arg("K"),
           py::arg("N"),
           py::arg("sigma"),
           py::arg("frozen_bit_gen") = ::gr::fec_dev::Polar::_frozen_bit_gen_t::GA_ARIKAN,
           py::arg("noise_type") = ::gr::fec_dev::Polar::_noise_t::Sigma,
           py::arg("decoder_type") = ::gr::fec_dev::Polar::_decoder_t::SC,
           py::arg("dec_impl") = ::gr::fec_dev::Decoder::_decoder_impl_t::NAIVE,
           py::arg("quant_fixed_point_pos") = 2,
           py::arg("quant_saturation_pos") = 6,
           py::arg("quant_impl") = ::gr::fec_dev::Quantizer::_quantizer_impl_t::STD,
           D(polar_decoder_aff3ct,make)
        )

        .def("set_frame_size",
            &polar_decoder_aff3ct::set_frame_size,
            py::arg("frame_size"),
            D(polar_decoder_aff3ct, set_frame_size))

        .def("rate", &polar_decoder_aff3ct::rate, D(polar_decoder_aff3ct, rate))

        ;
}








