/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(polar_encoder_aff3ct.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(571703c72ceeb85dc87a994d75e44a8c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/polar_encoder_aff3ct.h>
// pydoc.h is automatically generated in the build directory
#include <polar_encoder_aff3ct_pydoc.h>

void bind_polar_encoder_aff3ct(py::module& m)
{
    using polar_encoder_aff3ct = ::gr::fec_dev::polar_encoder_aff3ct;


    py::class_<polar_encoder_aff3ct, gr::fec::generic_encoder,
        std::shared_ptr<polar_encoder_aff3ct>>(m, "polar_encoder_aff3ct", D(polar_encoder_aff3ct))

        .def_static("make", &polar_encoder_aff3ct::make,
           py::arg("frame_size"),
           D(polar_encoder_aff3ct,make)
        )

        .def("set_frame_size",
            &polar_encoder_aff3ct::set_frame_size,
            py::arg("frame_size"),
            D(polar_encoder_aff3ct, set_frame_size))

        .def("rate", &polar_encoder_aff3ct::rate, D(polar_encoder_aff3ct, rate))

        ;
}








