/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rs_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2094150cc0304f9cfb51a68b87df455a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/rs_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <rs_decoder_pydoc.h>

void bind_rs_decoder(py::module& m)
{
    using rs_decoder = ::gr::fec_dev::rs_decoder;


    py::class_<rs_decoder, gr::fec::generic_decoder,
        std::shared_ptr<rs_decoder>>(m, "rs_decoder", D(rs_decoder))

        .def_static("make", &rs_decoder::make,
           py::arg("frame_size"),
           D(rs_decoder,make)
        )

        .def("set_frame_size",
            &rs_decoder::set_frame_size,
            py::arg("frame_size"),
            D(rs_decoder, set_frame_size))

        .def("rate", &rs_decoder::rate, D(rs_decoder, rate))

        ;
}







