/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rsc_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(56cd5049abc165a1634e9cbd5628993d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/rsc_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <rsc_encoder_pydoc.h>

void bind_rsc_encoder(py::module& m)
{
    using rsc_encoder = ::gr::fec_dev::rsc_encoder;


    py::class_<rsc_encoder, gr::fec::generic_encoder,
        std::shared_ptr<rsc_encoder>>(m, "rsc_encoder", D(rsc_encoder))

        .def_static("make", &rsc_encoder::make,
           py::arg("frame_size"),
           D(rsc_encoder,make)
        )

        .def("set_frame_size",
            &rsc_encoder::set_frame_size,
            py::arg("frame_size"),
            D(rsc_encoder, set_frame_size))

        .def("rate", &rsc_encoder::rate, D(rsc_encoder, rate))

        ;
}








