/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rsc_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e8fecf703812287a35544f0be802ee07)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/rsc_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <rsc_decoder_pydoc.h>

void bind_rsc_decoder(py::module& m)
{
    using rsc_decoder = ::gr::fec_dev::rsc_decoder;


    py::class_<rsc_decoder, gr::fec::generic_decoder,
        std::shared_ptr<rsc_decoder>>(m, "rsc_decoder", D(rsc_decoder))

        .def_static("make", &rsc_decoder::make,
           py::arg("frame_size"),
           D(rsc_decoder,make)
        )

        .def("set_frame_size",
            &rsc_decoder::set_frame_size,
            py::arg("frame_size"),
            D(rsc_decoder, set_frame_size))

        .def("rate", &rsc_decoder::rate, D(rsc_decoder, rate))

        ;
}








