/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(turbo_common.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b4884206bcee5cef766af0d913c6797a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec_dev/turbo_common.h>
// pydoc.h is automatically generated in the build directory
#include <turbo_common_pydoc.h>

void bind_turbo_common(py::module& m)
{
    py::enum_<::gr::fec_dev::_enc_standard_t>(m, "_enc_standard_t")
        .value("LTE", ::gr::fec_dev::_enc_standard_t::LTE)
        .value("CCSDS", ::gr::fec_dev::_enc_standard_t::CCSDS)
        .value("CUSTOM", ::gr::fec_dev::_enc_standard_t::CUSTOM)
        .export_values();
    py::implicitly_convertible<int, ::gr::fec_dev::_enc_standard_t>();

    py::enum_<::gr::fec_dev::_subenc_implem_t>(m, "_subenc_implem_t")
        .value("sys", ::gr::fec_dev::_subenc_implem_t::sys)
        .value("generic_sys", ::gr::fec_dev::_subenc_implem_t::generic_sys)
        .export_values();
    py::implicitly_convertible<int, ::gr::fec_dev::_subenc_implem_t>();
}
